### ISSUE TITLE
distributor error: "Failed to find scheduler that fits scheduler"

### ISSUE THREAD

**Issue by helloliuyiyang** [futurewei-cloud/global-resource-scheduler#261]
**What happened**:
When I launch the component in the following order：
1. Create Distributor
2. Create Scheduler
3. Create Dispatcher
4. Create Cluster
   -- wait siteinfo
5. Create Pods
Distributor may reporte error: "Failed to find scheduler that fits scheduler with the error failed to find a scheduler that fits pod".
This phenomenon appeared by chance.

**How to reproduce it (as minimally and precisely as possible)**:
I will provide details later, thanks.

**Comment by jshaofuturewei** [comment]
If we create 2 schedulers first and then create 1 cluster, according to the current logic, the cluster can't be assigned to the 2 schedulers and therefore the distributors failed to find schedulers that fit since both schedulers don't have clusters to assign pods.

It also happens to the case that the existing scheduler number is more than the cluster number

I updated the logic in the PR #265
