### ISSUE TITLE
Cluster CRD creation/deletion ---implement the controller logic

### ISSUE THREAD

**Issue by cathyhongzhang** [futurewei-cloud/global-resource-scheduler#27]
**What would you like to be added**:

**Why is this needed**:

**Comment by cathyhongzhang** [comment]
20% done

**Comment by kimeunju108** [comment]
Progress: 22% completed 

Controller Logic
(1) cluster creation:
- List/watch the cluster object creation through Informer.
- Run consistent hashing algorithm to select the home scheduler for this cluster.
- Save the cluster-scheduler binding to ETCD. That is, update the selected scheduler object to add the binding of this cluster to the scheduler.
- Add the cluster's geolocation and resource profile information to the selected scheduler object.

(2) cluster deletion:
- List/watch the cluster object deletion through Informer.
- Run consistent hashing algorithm to retrieve the home scheduler for this cluster.
- Remove the cluster-scheduler binding in ETCD. That is, update the selected scheduler object to remove the binding of this cluster to the scheduler.
- Remove the cluster's geolocation and resource profile information from the selected scheduler object. Since a scheduler could be tagged with multiple geolocations and many resource attributes, care must be taken not to remove a geolocation or resource attribute that is shared by another cluster bound to that scheduler object.

[Source] https://github.com/futurewei-cloud/global-resource-scheduler/blob/master/docs/design-proposals/global-scheduler/GlobalResourceScheduler-ClusterCrdController-ver0.1.md

**Comment by kimeunju108** [comment]
Progress: 25% completed

**Comment by cathyhongzhang** [comment]
27% completed.

**Comment by kimeunju108** [comment]
Progress: 35% completed

**Comment by cathyhongzhang** [comment]
coding for watching of cluster registartion/unregistration and creating the cluster object in ETCD are completed. working on UT scripts. The other cluster-scheduler binding logic (bullet 2~4) will be done by Kevin

**Comment by kimeunju108** [comment]
Progress: 80% completed - Implemented unit test

**Comment by cathyhongzhang** [comment]
will start to work on the interface design between the cluster controller and resoruce collector. The cluster controller will implement both gRPC server and client.

**Comment by cathyhongzhang** [comment]
has sent design draft to cathy and team for review

**Comment by cathyhongzhang** [comment]
CAthy has finished review of the draft and sent back to Kim. Kim will create a PR for this today. The start implement the logic

**Comment by kimeunju108** [comment]
PR 97: Issue 27 (before merging with issue #97 & 98) 
PR 98: updated gRPC design document 
In progress (30%)
- implemented gRPC proto according the design

**Comment by cathyhongzhang** [comment]
controller logic code 30% done

**Comment by kimeunju108** [comment]
controller logic code 40% done

**Comment by kimeunju108** [comment]
controller logic code 50% done 
- implemented client and server 
- testing communication between client and server

**Comment by kimeunju108** [comment]
controller logic code 60% done

Tested gRPC client and server for nested structure communication
Implementing gRPC adaptor for cluster controller & resource collector

**Comment by kimeunju108** [comment]
controller logic code 80% done 
- Implemented gRPC module

**Comment by kimeunju108** [comment]
controller logic code 85% done

Implemented gRPC client- sending cluster profile to resource collector
Issue: arktos/vendor version conflict ==> resolved & made a new PR #115
Implementing gRPC server-receiving cluster state from resource collector

**Comment by cathyhongzhang** [comment]
check against the scheduler code to make sure the cluster controller provides all the static cluster information the scheduler needs.

**Comment by cathyhongzhang** [comment]
completed
